import React, { useState } from 'react';
import { AlertsTable } from '../components/AlertsTable';
import { SearchIcon, FilterIcon } from '../components/Icons';

export function AlertsPage({ alertsData = [] }) {
  const [searchFilter, setSearchFilter] = useState('');
  const [severityFilter, setSeverityFilter] = useState('ALL');

  const filteredAlerts = alertsData.filter((a) => {
    const matchesSearch =
      searchFilter === '' ||
      a.source_ip.includes(searchFilter) ||
      a.destination_ip.includes(searchFilter) ||
      a.attack_type.toLowerCase().includes(searchFilter.toLowerCase()) ||
      a.id.toLowerCase().includes(searchFilter.toLowerCase());

    const matchesSeverity =
      severityFilter === 'ALL' ||
      String(a.severity).toUpperCase() === severityFilter.toUpperCase();

    return matchesSearch && matchesSeverity;
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div className="soc-card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#F8FAFC' }}>Security Incident Alerts Log</h3>
          <p style={{ fontSize: '0.8rem', color: '#94A3B8' }}>Automated incident alert logs generated by the Extra Trees live detection engine.</p>
        </div>

        {/* Filter Controls */}
        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          <div style={{ position: 'relative' }}>
            <input
              type="text"
              placeholder="Search IP, Attack, ID..."
              value={searchFilter}
              onChange={(e) => setSearchFilter(e.target.value)}
              className="select-input"
              style={{ paddingLeft: '2.2rem', width: '220px' }}
            />
            <div style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }}>
              <SearchIcon size={14} color="#64748B" />
            </div>
          </div>

          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="select-input"
          >
            <option value="ALL">All Severities</option>

            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>
        </div>
      </div>

      <AlertsTable alerts={filteredAlerts} />
    </div>
  );
}
